//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceOpenStreetMap
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Branch", Namespace="http://schemas.datacontract.org/2004/07/ServiceOpenStreetMap")]
    public partial class Branch : object
    {
        
        private string CodeField;
        
        private float LatitudeField;
        
        private float LongitudeField;
        
        private string PscField;
        
        private string StreetField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Latitude
        {
            get
            {
                return this.LatitudeField;
            }
            set
            {
                this.LatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Longitude
        {
            get
            {
                return this.LongitudeField;
            }
            set
            {
                this.LongitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Psc
        {
            get
            {
                return this.PscField;
            }
            set
            {
                this.PscField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street
        {
            get
            {
                return this.StreetField;
            }
            set
            {
                this.StreetField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Coordinates", Namespace="http://schemas.datacontract.org/2004/07/ServiceOpenStreetMap")]
    public partial class Coordinates : object
    {
        
        private double LatitudeField;
        
        private double LongitudeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude
        {
            get
            {
                return this.LatitudeField;
            }
            set
            {
                this.LatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude
        {
            get
            {
                return this.LongitudeField;
            }
            set
            {
                this.LongitudeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeocodeResponse", Namespace="http://schemas.datacontract.org/2004/07/ServiceOpenStreetMap.Geocoding.Models")]
    public partial class GeocodeResponse : ServiceOpenStreetMap.BaseNominatimResponse
    {
        
        private string GeoKMLField;
        
        private string GeoSVGField;
        
        private string GeoTextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GeoKML
        {
            get
            {
                return this.GeoKMLField;
            }
            set
            {
                this.GeoKMLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GeoSVG
        {
            get
            {
                return this.GeoSVGField;
            }
            set
            {
                this.GeoSVGField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GeoText
        {
            get
            {
                return this.GeoTextField;
            }
            set
            {
                this.GeoTextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseNominatimResponse", Namespace="http://schemas.datacontract.org/2004/07/ServiceOpenStreetMap.Geocoding.Models")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceOpenStreetMap.GeocodeResponse))]
    public partial class BaseNominatimResponse : object
    {
        
        private ServiceOpenStreetMap.AddressResult AddressField;
        
        private string AddresstypeField;
        
        private System.Collections.Generic.Dictionary<string, string> AlternateNamesField;
        
        private string CategoryField;
        
        private string ClassField;
        
        private string ClassTypeField;
        
        private string DisplayNameField;
        
        private System.Collections.Generic.Dictionary<string, string> ExtraTagsField;
        
        private string IconURLField;
        
        private double ImportanceField;
        
        private double LatitudeField;
        
        private string LicenseField;
        
        private double LongitudeField;
        
        private long OSMIDField;
        
        private string OSMTypeField;
        
        private int PlaceIDField;
        
        private string PlaceRankField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceOpenStreetMap.AddressResult Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Addresstype
        {
            get
            {
                return this.AddresstypeField;
            }
            set
            {
                this.AddresstypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> AlternateNames
        {
            get
            {
                return this.AlternateNamesField;
            }
            set
            {
                this.AlternateNamesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category
        {
            get
            {
                return this.CategoryField;
            }
            set
            {
                this.CategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Class
        {
            get
            {
                return this.ClassField;
            }
            set
            {
                this.ClassField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClassType
        {
            get
            {
                return this.ClassTypeField;
            }
            set
            {
                this.ClassTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName
        {
            get
            {
                return this.DisplayNameField;
            }
            set
            {
                this.DisplayNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> ExtraTags
        {
            get
            {
                return this.ExtraTagsField;
            }
            set
            {
                this.ExtraTagsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IconURL
        {
            get
            {
                return this.IconURLField;
            }
            set
            {
                this.IconURLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Importance
        {
            get
            {
                return this.ImportanceField;
            }
            set
            {
                this.ImportanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude
        {
            get
            {
                return this.LatitudeField;
            }
            set
            {
                this.LatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string License
        {
            get
            {
                return this.LicenseField;
            }
            set
            {
                this.LicenseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude
        {
            get
            {
                return this.LongitudeField;
            }
            set
            {
                this.LongitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long OSMID
        {
            get
            {
                return this.OSMIDField;
            }
            set
            {
                this.OSMIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OSMType
        {
            get
            {
                return this.OSMTypeField;
            }
            set
            {
                this.OSMTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlaceID
        {
            get
            {
                return this.PlaceIDField;
            }
            set
            {
                this.PlaceIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlaceRank
        {
            get
            {
                return this.PlaceRankField;
            }
            set
            {
                this.PlaceRankField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressResult", Namespace="http://schemas.datacontract.org/2004/07/ServiceOpenStreetMap.Geocoding.Models")]
    public partial class AddressResult : object
    {
        
        private string CityField;
        
        private string CountryField;
        
        private string CountryCodeField;
        
        private string CountyField;
        
        private string DistrictField;
        
        private string HamletField;
        
        private string HouseNumberField;
        
        private string NameField;
        
        private string NeighborhoodField;
        
        private string PedestrianField;
        
        private string PostCodeField;
        
        private string RegionField;
        
        private string RoadField;
        
        private string StateField;
        
        private string SuburbField;
        
        private string TownField;
        
        private string VillageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryCode
        {
            get
            {
                return this.CountryCodeField;
            }
            set
            {
                this.CountryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string County
        {
            get
            {
                return this.CountyField;
            }
            set
            {
                this.CountyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string District
        {
            get
            {
                return this.DistrictField;
            }
            set
            {
                this.DistrictField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hamlet
        {
            get
            {
                return this.HamletField;
            }
            set
            {
                this.HamletField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HouseNumber
        {
            get
            {
                return this.HouseNumberField;
            }
            set
            {
                this.HouseNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Neighborhood
        {
            get
            {
                return this.NeighborhoodField;
            }
            set
            {
                this.NeighborhoodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pedestrian
        {
            get
            {
                return this.PedestrianField;
            }
            set
            {
                this.PedestrianField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostCode
        {
            get
            {
                return this.PostCodeField;
            }
            set
            {
                this.PostCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Region
        {
            get
            {
                return this.RegionField;
            }
            set
            {
                this.RegionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Road
        {
            get
            {
                return this.RoadField;
            }
            set
            {
                this.RoadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Suburb
        {
            get
            {
                return this.SuburbField;
            }
            set
            {
                this.SuburbField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Town
        {
            get
            {
                return this.TownField;
            }
            set
            {
                this.TownField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Village
        {
            get
            {
                return this.VillageField;
            }
            set
            {
                this.VillageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceOpenStreetMap.IServiceOpenStreetMap")]
    public interface IServiceOpenStreetMap
    {
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOpenStreetMap/ResolveBranchCode", ReplyAction="http://tempuri.org/IServiceOpenStreetMap/ResolveBranchCodeResponse")]
        System.Threading.Tasks.Task<ServiceOpenStreetMap.ResolveBranchCodeResponse> ResolveBranchCodeAsync(ServiceOpenStreetMap.ResolveBranchCodeRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOpenStreetMap/GetClosestPoint", ReplyAction="http://tempuri.org/IServiceOpenStreetMap/GetClosestPointResponse")]
        System.Threading.Tasks.Task<ServiceOpenStreetMap.GetClosestPointResponse> GetClosestPointAsync(ServiceOpenStreetMap.GetClosestPointRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOpenStreetMap/GetCoordinates", ReplyAction="http://tempuri.org/IServiceOpenStreetMap/GetCoordinatesResponse")]
        System.Threading.Tasks.Task<ServiceOpenStreetMap.GeocodeResponse[]> GetCoordinatesAsync(string address);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResolveBranchCode", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ResolveBranchCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string street;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string city;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string streetNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string zip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public ServiceOpenStreetMap.Branch[] branches;
        
        public ResolveBranchCodeRequest()
        {
        }
        
        public ResolveBranchCodeRequest(string street, string city, string streetNumber, string zip, ServiceOpenStreetMap.Branch[] branches)
        {
            this.street = street;
            this.city = city;
            this.streetNumber = streetNumber;
            this.zip = zip;
            this.branches = branches;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResolveBranchCodeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ResolveBranchCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ResolveBranchCodeResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string branch;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strError;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string strMessage;
        
        public ResolveBranchCodeResponse()
        {
        }
        
        public ResolveBranchCodeResponse(bool ResolveBranchCodeResult, string branch, string strError, string strMessage)
        {
            this.ResolveBranchCodeResult = ResolveBranchCodeResult;
            this.branch = branch;
            this.strError = strError;
            this.strMessage = strMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClosestPoint", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetClosestPointRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceOpenStreetMap.Coordinates coordinates;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ServiceOpenStreetMap.Coordinates[] others;
        
        public GetClosestPointRequest()
        {
        }
        
        public GetClosestPointRequest(ServiceOpenStreetMap.Coordinates coordinates, ServiceOpenStreetMap.Coordinates[] others)
        {
            this.coordinates = coordinates;
            this.others = others;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClosestPointResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetClosestPointResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public double GetClosestPointResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ServiceOpenStreetMap.Coordinates closestPoint;
        
        public GetClosestPointResponse()
        {
        }
        
        public GetClosestPointResponse(double GetClosestPointResult, ServiceOpenStreetMap.Coordinates closestPoint)
        {
            this.GetClosestPointResult = GetClosestPointResult;
            this.closestPoint = closestPoint;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IServiceOpenStreetMapChannel : ServiceOpenStreetMap.IServiceOpenStreetMap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ServiceOpenStreetMapClient : System.ServiceModel.ClientBase<ServiceOpenStreetMap.IServiceOpenStreetMap>, ServiceOpenStreetMap.IServiceOpenStreetMap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceOpenStreetMapClient() : 
                base(ServiceOpenStreetMapClient.GetDefaultBinding(), ServiceOpenStreetMapClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiceOpenStreetMap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceOpenStreetMapClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceOpenStreetMapClient.GetBindingForEndpoint(endpointConfiguration), ServiceOpenStreetMapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceOpenStreetMapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceOpenStreetMapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceOpenStreetMapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceOpenStreetMapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceOpenStreetMapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceOpenStreetMap.ResolveBranchCodeResponse> ResolveBranchCodeAsync(ServiceOpenStreetMap.ResolveBranchCodeRequest request)
        {
            return base.Channel.ResolveBranchCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceOpenStreetMap.GetClosestPointResponse> GetClosestPointAsync(ServiceOpenStreetMap.GetClosestPointRequest request)
        {
            return base.Channel.GetClosestPointAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceOpenStreetMap.GeocodeResponse[]> GetCoordinatesAsync(string address)
        {
            return base.Channel.GetCoordinatesAsync(address);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceOpenStreetMap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceOpenStreetMap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:61076/ServiceOpenStreetMap.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceOpenStreetMapClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiceOpenStreetMap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceOpenStreetMapClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiceOpenStreetMap);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiceOpenStreetMap,
        }
    }
}
